/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThemeRouteImport } from './routes/theme'
import { Route as DocsLayoutRouteImport } from './routes/_docsLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsLayoutDocsSplatRouteImport } from './routes/_docsLayout/docs/$'

const ThemeRoute = ThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLayoutRoute = DocsLayoutRouteImport.update({
  id: '/_docsLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLayoutDocsSplatRoute = DocsLayoutDocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => DocsLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/theme': typeof ThemeRoute
  '/docs/$': typeof DocsLayoutDocsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/theme': typeof ThemeRoute
  '/docs/$': typeof DocsLayoutDocsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_docsLayout': typeof DocsLayoutRouteWithChildren
  '/theme': typeof ThemeRoute
  '/_docsLayout/docs/$': typeof DocsLayoutDocsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/theme' | '/docs/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/theme' | '/docs/$'
  id: '__root__' | '/' | '/_docsLayout' | '/theme' | '/_docsLayout/docs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsLayoutRoute: typeof DocsLayoutRouteWithChildren
  ThemeRoute: typeof ThemeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docsLayout': {
      id: '/_docsLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_docsLayout/docs/$': {
      id: '/_docsLayout/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsLayoutDocsSplatRouteImport
      parentRoute: typeof DocsLayoutRoute
    }
  }
}

interface DocsLayoutRouteChildren {
  DocsLayoutDocsSplatRoute: typeof DocsLayoutDocsSplatRoute
}

const DocsLayoutRouteChildren: DocsLayoutRouteChildren = {
  DocsLayoutDocsSplatRoute: DocsLayoutDocsSplatRoute,
}

const DocsLayoutRouteWithChildren = DocsLayoutRoute._addFileChildren(
  DocsLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsLayoutRoute: DocsLayoutRouteWithChildren,
  ThemeRoute: ThemeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
